[package]
name = "solarville"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
# spacetimedb = "0.8.0"
spacetimedb = { git = "https://github.com/ClockworkLabs/SpacetimeDB" }
log = "0.4"
# rand = "0.8.5"
