// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ProductType,
  ProductTypeElement,
  SumType,
  SumTypeVariant,
} from "@clockworklabs/spacetimedb-sdk";

/**
 * Reducer arguments for SaveMicroprocessCode
 */
export class SaveMicroprocessCode {
  constructor(
    public name: string,
    public file_path: string,
    public code_content: string,
  ) {}

  static getTypeScriptAlgebraicType(): AlgebraicType {
    return new ProductType([
      new ProductTypeElement("name", AlgebraicType.createPrimitive("String")),
      new ProductTypeElement("file_path", AlgebraicType.createPrimitive("String")),
      new ProductTypeElement("code_content", AlgebraicType.createPrimitive("String")),
    ]);
  }

  static fromAlgebraicValue(value: AlgebraicValue): SaveMicroprocessCode {
    const elements = value.getElementsOfProductValue();
    const name = elements[0].getValueAsString();
    const file_path = elements[1].getValueAsString();
    const code_content = elements[2].getValueAsString();
    return new SaveMicroprocessCode(name, file_path, code_content);
  }
}
