// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ProductType,
  ProductTypeElement,
  SumType,
  SumTypeVariant,
} from "@clockworklabs/spacetimedb-sdk";

/**
 * Reducer arguments for StartMicroprocess
 */
export class StartMicroprocess {
  constructor(
    public code_id: number,
  ) {}

  static getTypeScriptAlgebraicType(): AlgebraicType {
    return new ProductType([
      new ProductTypeElement("code_id", AlgebraicType.createPrimitive("u32")),
    ]);
  }

  static fromAlgebraicValue(value: AlgebraicValue): StartMicroprocess {
    const elements = value.getElementsOfProductValue();
    const code_id = elements[0].getValueAsU32();
    return new StartMicroprocess(code_id);
  }
}
