// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ProductType,
  ProductTypeElement,
  SumType,
  SumTypeVariant,
} from "@clockworklabs/spacetimedb-sdk";

/**
 * Reducer arguments for UpdateMicroprocessState
 */
export class UpdateMicroprocessState {
  constructor(
    public code_id: number,
    public left_motor_speed: number,
    public right_motor_speed: number,
    public error_message: string,
    public is_running: boolean,
  ) {}

  static getTypeScriptAlgebraicType(): AlgebraicType {
    return new ProductType([
      new ProductTypeElement("code_id", AlgebraicType.createPrimitive("u32")),
      new ProductTypeElement("left_motor_speed", AlgebraicType.createPrimitive("f32")),
      new ProductTypeElement("right_motor_speed", AlgebraicType.createPrimitive("f32")),
      new ProductTypeElement("error_message", AlgebraicType.createPrimitive("String")),
      new ProductTypeElement("is_running", AlgebraicType.createPrimitive("Bool")),
    ]);
  }

  static fromAlgebraicValue(value: AlgebraicValue): UpdateMicroprocessState {
    const elements = value.getElementsOfProductValue();
    const code_id = elements[0].getValueAsU32();
    const left_motor_speed = elements[1].getValueAsF32();
    const right_motor_speed = elements[2].getValueAsF32();
    const error_message = elements[3].getValueAsString();
    const is_running = elements[4].getValueAsBool();
    return new UpdateMicroprocessState(code_id, left_motor_speed, right_motor_speed, error_message, is_running);
  }
}
