// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";

export type UpdateMicroprocessState = {
  codeId: number,
  leftMotorSpeed: number,
  rightMotorSpeed: number,
  errorMessage: string,
  isRunning: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace UpdateMicroprocessState {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("codeId", AlgebraicType.createU32Type()),
      new ProductTypeElement("leftMotorSpeed", AlgebraicType.createF32Type()),
      new ProductTypeElement("rightMotorSpeed", AlgebraicType.createF32Type()),
      new ProductTypeElement("errorMessage", AlgebraicType.createStringType()),
      new ProductTypeElement("isRunning", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: UpdateMicroprocessState): void {
    UpdateMicroprocessState.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): UpdateMicroprocessState {
    return UpdateMicroprocessState.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

