// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MicroprocessStateHandle : RemoteTableHandle<EventContext, MicroprocessState>
        {
            protected override string RemoteTableName => "microprocess_state";

            public sealed class CodeIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(MicroprocessState row) => row.CodeId;

                public CodeIdIndex(MicroprocessStateHandle table) : base(table) { }
            }

            public readonly CodeIdIndex CodeId;

            public sealed class StateIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MicroprocessState row) => row.StateId;

                public StateIdUniqueIndex(MicroprocessStateHandle table) : base(table) { }
            }

            public readonly StateIdUniqueIndex StateId;

            internal MicroprocessStateHandle(DbConnection conn) : base(conn)
            {
                CodeId = new(this);
                StateId = new(this);
            }

            protected override object GetPrimaryKey(MicroprocessState row) => row.StateId;
        }

        public readonly MicroprocessStateHandle MicroprocessState;
    }
}
