// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class MicroprocessCodeHandle : RemoteTableHandle<EventContext, MicroprocessCode>
        {
            protected override string RemoteTableName => "microprocess_code";

            public sealed class CodeIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(MicroprocessCode row) => row.CodeId;

                public CodeIdUniqueIndex(MicroprocessCodeHandle table) : base(table) { }
            }

            public readonly CodeIdUniqueIndex CodeId;

            public sealed class OwnerIdIndex : BTreeIndexBase<uint>
            {
                protected override uint GetKey(MicroprocessCode row) => row.OwnerId;

                public OwnerIdIndex(MicroprocessCodeHandle table) : base(table) { }
            }

            public readonly OwnerIdIndex OwnerId;

            internal MicroprocessCodeHandle(DbConnection conn) : base(conn)
            {
                CodeId = new(this);
                OwnerId = new(this);
            }

            protected override object GetPrimaryKey(MicroprocessCode row) => row.CodeId;
        }

        public readonly MicroprocessCodeHandle MicroprocessCode;
    }
}
