// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class UpdatePlayerTimerHandle : RemoteTableHandle<EventContext, UpdatePlayerTimer>
        {
            protected override string RemoteTableName => "update_player_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(UpdatePlayerTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(UpdatePlayerTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal UpdatePlayerTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(UpdatePlayerTimer row) => row.ScheduledId;
        }

        public readonly UpdatePlayerTimerHandle UpdatePlayerTimer;
    }
}
