// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void AddMicroprocessCodeHandler(ReducerEventContext ctx, string name, string codeContent, string filePath);
        public event AddMicroprocessCodeHandler? OnAddMicroprocessCode;

        public void AddMicroprocessCode(string name, string codeContent, string filePath)
        {
            conn.InternalCallReducer(new Reducer.AddMicroprocessCode(name, codeContent, filePath), this.SetCallReducerFlags.AddMicroprocessCodeFlags);
        }

        public bool InvokeAddMicroprocessCode(ReducerEventContext ctx, Reducer.AddMicroprocessCode args)
        {
            if (OnAddMicroprocessCode == null) return false;
            OnAddMicroprocessCode(
                ctx,
                args.Name,
                args.CodeContent,
                args.FilePath
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class AddMicroprocessCode : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "code_content")]
            public string CodeContent;
            [DataMember(Name = "file_path")]
            public string FilePath;

            public AddMicroprocessCode(
                string Name,
                string CodeContent,
                string FilePath
            )
            {
                this.Name = Name;
                this.CodeContent = CodeContent;
                this.FilePath = FilePath;
            }

            public AddMicroprocessCode()
            {
                this.Name = "";
                this.CodeContent = "";
                this.FilePath = "";
            }

            string IReducerArgs.ReducerName => "add_microprocess_code";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags AddMicroprocessCodeFlags;
        public void AddMicroprocessCode(CallReducerFlags flags) => AddMicroprocessCodeFlags = flags;
    }
}
