// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void RegisterPlayerHandler(ReducerEventContext ctx, string name, DbVector3 position, DbVector3 rotation);
        public event RegisterPlayerHandler? OnRegisterPlayer;

        public void RegisterPlayer(string name, DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.RegisterPlayer(name, position, rotation), this.SetCallReducerFlags.RegisterPlayerFlags);
        }

        public bool InvokeRegisterPlayer(ReducerEventContext ctx, Reducer.RegisterPlayer args)
        {
            if (OnRegisterPlayer == null) return false;
            OnRegisterPlayer(
                ctx,
                args.Name,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class RegisterPlayer : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public RegisterPlayer(
                string Name,
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.Name = Name;
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public RegisterPlayer()
            {
                this.Name = "";
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "register_player";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags RegisterPlayerFlags;
        public void RegisterPlayer(CallReducerFlags flags) => RegisterPlayerFlags = flags;
    }
}
