// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StartMicroprocessHandler(ReducerEventContext ctx, uint codeId);
        public event StartMicroprocessHandler? OnStartMicroprocess;

        public void StartMicroprocess(uint codeId)
        {
            conn.InternalCallReducer(new Reducer.StartMicroprocess(codeId), this.SetCallReducerFlags.StartMicroprocessFlags);
        }

        public bool InvokeStartMicroprocess(ReducerEventContext ctx, Reducer.StartMicroprocess args)
        {
            if (OnStartMicroprocess == null) return false;
            OnStartMicroprocess(
                ctx,
                args.CodeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StartMicroprocess : Reducer, IReducerArgs
        {
            [DataMember(Name = "code_id")]
            public uint CodeId;

            public StartMicroprocess(uint CodeId)
            {
                this.CodeId = CodeId;
            }

            public StartMicroprocess()
            {
            }

            string IReducerArgs.ReducerName => "start_microprocess";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StartMicroprocessFlags;
        public void StartMicroprocess(CallReducerFlags flags) => StartMicroprocessFlags = flags;
    }
}
