// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void StopMicroprocessHandler(ReducerEventContext ctx, uint codeId);
        public event StopMicroprocessHandler? OnStopMicroprocess;

        public void StopMicroprocess(uint codeId)
        {
            conn.InternalCallReducer(new Reducer.StopMicroprocess(codeId), this.SetCallReducerFlags.StopMicroprocessFlags);
        }

        public bool InvokeStopMicroprocess(ReducerEventContext ctx, Reducer.StopMicroprocess args)
        {
            if (OnStopMicroprocess == null) return false;
            OnStopMicroprocess(
                ctx,
                args.CodeId
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class StopMicroprocess : Reducer, IReducerArgs
        {
            [DataMember(Name = "code_id")]
            public uint CodeId;

            public StopMicroprocess(uint CodeId)
            {
                this.CodeId = CodeId;
            }

            public StopMicroprocess()
            {
            }

            string IReducerArgs.ReducerName => "stop_microprocess";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags StopMicroprocessFlags;
        public void StopMicroprocess(CallReducerFlags flags) => StopMicroprocessFlags = flags;
    }
}
