// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdatePlayerPositionHandler(ReducerEventContext ctx, DbVector3 position, DbVector3 rotation);
        public event UpdatePlayerPositionHandler? OnUpdatePlayerPosition;

        public void UpdatePlayerPosition(DbVector3 position, DbVector3 rotation)
        {
            conn.InternalCallReducer(new Reducer.UpdatePlayerPosition(position, rotation), this.SetCallReducerFlags.UpdatePlayerPositionFlags);
        }

        public bool InvokeUpdatePlayerPosition(ReducerEventContext ctx, Reducer.UpdatePlayerPosition args)
        {
            if (OnUpdatePlayerPosition == null) return false;
            OnUpdatePlayerPosition(
                ctx,
                args.Position,
                args.Rotation
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdatePlayerPosition : Reducer, IReducerArgs
        {
            [DataMember(Name = "position")]
            public DbVector3 Position;
            [DataMember(Name = "rotation")]
            public DbVector3 Rotation;

            public UpdatePlayerPosition(
                DbVector3 Position,
                DbVector3 Rotation
            )
            {
                this.Position = Position;
                this.Rotation = Rotation;
            }

            public UpdatePlayerPosition()
            {
                this.Position = new();
                this.Rotation = new();
            }

            string IReducerArgs.ReducerName => "update_player_position";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdatePlayerPositionFlags;
        public void UpdatePlayerPosition(CallReducerFlags flags) => UpdatePlayerPositionFlags = flags;
    }
}
