// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void UpdateMicroprocessCodeHandler(ReducerEventContext ctx, string name, string filePath, string codeContent);
        public event UpdateMicroprocessCodeHandler? OnUpdateMicroprocessCode;

        public void UpdateMicroprocessCode(string name, string filePath, string codeContent)
        {
            conn.InternalCallReducer(new Reducer.UpdateMicroprocessCode(name, filePath, codeContent), this.SetCallReducerFlags.UpdateMicroprocessCodeFlags);
        }

        public bool InvokeUpdateMicroprocessCode(ReducerEventContext ctx, Reducer.UpdateMicroprocessCode args)
        {
            if (OnUpdateMicroprocessCode == null) return false;
            OnUpdateMicroprocessCode(
                ctx,
                args.Name,
                args.FilePath,
                args.CodeContent
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class UpdateMicroprocessCode : Reducer, IReducerArgs
        {
            [DataMember(Name = "name")]
            public string Name;
            [DataMember(Name = "file_path")]
            public string FilePath;
            [DataMember(Name = "code_content")]
            public string CodeContent;

            public UpdateMicroprocessCode(
                string Name,
                string FilePath,
                string CodeContent
            )
            {
                this.Name = Name;
                this.FilePath = FilePath;
                this.CodeContent = CodeContent;
            }

            public UpdateMicroprocessCode()
            {
                this.Name = "";
                this.FilePath = "";
                this.CodeContent = "";
            }

            string IReducerArgs.ReducerName => "update_microprocess_code";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags UpdateMicroprocessCodeFlags;
        public void UpdateMicroprocessCode(CallReducerFlags flags) => UpdateMicroprocessCodeFlags = flags;
    }
}
