// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MicroprocessCode
    {
        [DataMember(Name = "code_id")]
        public uint CodeId;
        [DataMember(Name = "owner_id")]
        public uint OwnerId;
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "file_path")]
        public string FilePath;
        [DataMember(Name = "code_content")]
        public string CodeContent;
        [DataMember(Name = "last_updated")]
        public SpacetimeDB.Timestamp LastUpdated;

        public MicroprocessCode(
            uint CodeId,
            uint OwnerId,
            string Name,
            string FilePath,
            string CodeContent,
            SpacetimeDB.Timestamp LastUpdated
        )
        {
            this.CodeId = CodeId;
            this.OwnerId = OwnerId;
            this.Name = Name;
            this.FilePath = FilePath;
            this.CodeContent = CodeContent;
            this.LastUpdated = LastUpdated;
        }

        public MicroprocessCode()
        {
            this.Name = "";
            this.FilePath = "";
            this.CodeContent = "";
        }
    }
}
