// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class MicroprocessState
    {
        [DataMember(Name = "state_id")]
        public uint StateId;
        [DataMember(Name = "code_id")]
        public uint CodeId;
        [DataMember(Name = "left_motor_speed")]
        public float LeftMotorSpeed;
        [DataMember(Name = "right_motor_speed")]
        public float RightMotorSpeed;
        [DataMember(Name = "error_message")]
        public string ErrorMessage;
        [DataMember(Name = "last_updated")]
        public SpacetimeDB.Timestamp LastUpdated;
        [DataMember(Name = "is_running")]
        public bool IsRunning;

        public MicroprocessState(
            uint StateId,
            uint CodeId,
            float LeftMotorSpeed,
            float RightMotorSpeed,
            string ErrorMessage,
            SpacetimeDB.Timestamp LastUpdated,
            bool IsRunning
        )
        {
            this.StateId = StateId;
            this.CodeId = CodeId;
            this.LeftMotorSpeed = LeftMotorSpeed;
            this.RightMotorSpeed = RightMotorSpeed;
            this.ErrorMessage = ErrorMessage;
            this.LastUpdated = LastUpdated;
            this.IsRunning = IsRunning;
        }

        public MicroprocessState()
        {
            this.ErrorMessage = "";
        }
    }
}
