// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class WorldConfig
    {
        [DataMember(Name = "id")]
        public uint Id;
        [DataMember(Name = "world_name")]
        public string WorldName;

        public WorldConfig(
            uint Id,
            string WorldName
        )
        {
            this.Id = Id;
            this.WorldName = WorldName;
        }

        public WorldConfig()
        {
            this.WorldName = "";
        }
    }
}
